config/routes.rb
Rails.application.routes.draw do
  scope '/system', :module => 'system_metrics' do
    get 'metrics/admin' => 'metrics#admin', :as => 'system_metrics_admin'
    get 'metrics/category/:category' => 'metrics#category', :as => 'system_metrics_category'
    resources :metrics, :only => [:index, :show, :destroy]
  end
end

app/models/system_metrics/metric.rb
module SystemMetrics
  class Metric < ActiveRecord::Base
    attr_accessible :name, :payload, :transaction_id, :duration, :action, :category, :children, :exclusive_duration, :started_at, :request_id, :parent_id

    set_table_name 'system_metrics'
    has_many :children, :class_name => self.name, :foreign_key => :parent_id
    belongs_to :parent, :class_name => self.name
    serialize :payload

    def ancestors
      ancestors = []
      metric = self
      while parent = metric.parent
        ancestors << parent
        metric = parent
      end
      ancestors
    end

    # Returns if the current node is the parent of the given node.
    # If this is a new record, we can use started_at values to detect parenting.
    # However, if it was already saved, we lose microseconds information from
    # timestamps and we must rely solely in id and parent_id information.
    def parent_of?(metric)
      if new_record?
        start = (started_at - metric.started_at) * 1000.0
        start <= 0 && (start + duration >= metric.duration)
      else
        self.id == metric.parent_id
      end
    end

    def child_of?(metric)
      metric.parent_of?(self)
    end
  end
end

app/controllers/system_metrics/metrics_controller.rb
module SystemMetrics
  class MetricsController < ActionController::Base
    def index
      @category_metrics = {}
      categories = SystemMetrics::Metric.select('DISTINCT(category)').order('category ASC').map(&:category)
      categories.each do |category|
        @category_metrics[category] = SystemMetrics::Metric.where(:category => category, :started_at => date_range).order('duration DESC').limit(limit(10))
      end
    end

    def show
      @metric = SystemMetrics::Metric.find(params[:id])
    end

    def destroy
      category = params[:id]
      if category == 'all'
        SystemMetrics::Metric.delete_all
      else
        SystemMetrics::Metric.where(:category => category).delete_all
      end

      redirect_to system_metrics_admin_path
    end

    def category
      @metrics = SystemMetrics::Metric.where(:category => params[:category], :started_at => date_range).order('duration DESC').limit(limit)
    end

    def admin
      @categories = SystemMetrics::Metric.select('category, count(category) as count').order('category ASC').group('category')
    end

    private
      def date_range
        from = params[:from] || '30.minutes'
        from_num, from_unit = from.split('.')
        @from_date = from_num.to_i.send(from_unit.to_sym).ago
        to = params[:to] || '0.minutes'
        to_num, to_unit = to.split('.')
        @to_date = to_num.to_i.send(to_unit.to_sym).ago
        @from_date..@to_date
      end

      def limit(default=100)
        @limit = params[:limit] || default
      end
  end
end

app/helpers/system_metrics/metrics_helper.rb
module SystemMetrics
  module MetricsHelper
    IDENTIFIER_ATTRS = [:end_point, :layout, :identifier, :path, :name]

    def set_title(title)
      content_for(:title, title.to_s)
    end

    def title
      content_for?(:title) ? content_for(:title) : 'System Metrics'
    end

    def set_page_title(page_title)
      content_for(:page_title, page_title.to_s)
    end

    def page_title
      content_for?(:page_title) ? content_for(:page_title) : ''
    end

    def identifier(metric)
      attr = IDENTIFIER_ATTRS.find { |attr| metric.payload.include?(attr) && metric.payload[attr] != nil }  
      attr.present? ? metric.payload[attr] : metric.name
    end

    def slow_threshold(metric)
      case metric.name
      when 'request.rack' then 500.0
      when 'process_action.action_controller' then 450.0
      when 'sql.active_record' then 150.0
      when /render_[^\.]+\.action_view/ then 250.0
      else 200.0
      end
    end
  end
end

app/views/layouts/system_metrics/metrics.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title><%= title %></title>
    <%= stylesheet_link_tag 'system_metrics/reset', 
      'system_metrics/typography',
      :media => 'screen, projection' %>
    <%= stylesheet_link_tag 'system_metrics/print', :media => 'print' %>
    <!--[if lt IE 8]>
    <%= stylesheet_link_tag 'system_metrics/ie', :media => 'screen, projection' %>
    <![endif]-->
    <%= stylesheet_link_tag 'system_metrics/app', :media => 'screen, projection' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="container">
      <div id="top">
        <div id="hd">
          <h1>System Metrics</h1>
          <%= render "menu" %>
        </div>
      </div>
      <div id="bd">
        <%= render "title_bar" %>
        <div id="content">
          <%= yield %>
        </div>
      </div>
    </div>
    <div id="ft">
      <span>Developed by <a href="http://www.nearinfinity.com">Near Infinity</a></span>
    </div>
  </body>
</html>

app/views/system_metrics/metrics/_menu.html.erb
<ul>
  <li><%= link_to 'Dashboard', metrics_path %></li>
<% for metric in SystemMetrics::Metric.select('DISTINCT(category)').order('category ASC') -%>
  <li><%= link_to metric.category.titleize, system_metrics_category_path(metric.category) %></li>
<% end -%>
  <li>|</li>
  <li><%= link_to 'Administration', system_metrics_admin_path %></li>
</ul>

app/views/system_metrics/metrics/_metric_row.html.erb
<tr>
  <td><%= link_to metric.id, metric_path(metric) %></td>
  <% if columns.include?(:name) %><td><%= ('&rarr; ' * indent).html_safe %><%= metric.name %></td><% end %>
  <% if columns.include?(:identifier) %><td><%= identifier(metric) %></td><% end %>
  <% if columns.include?(:action) %><td><%= metric.action %></td><% end %>
  <% if columns.include?(:when) %><td><%= distance_of_time_in_words_to_now metric.started_at %> ago</td><% end %>
  <% if columns.include?(:duration) %><td><span class="hbar<%= metric.duration > slow_threshold(metric) ? ' slow' : '' %>" style="width: <%= metric.duration / longest_duration * 100 %>%"></span><%= metric.duration %></td><% end %>
</tr>
<% if include_children -%>
<% for child_metric in metric.children -%>
  <%= render :partial => 'metric_row',:locals => {
    :indent => indent + 1,
    :columns => columns,
    :metric => child_metric,
    :longest_duration => longest_duration,
    :include_children => include_children
  } %>
<% end -%>
<% end -%>

app/views/system_metrics/metrics/_metric_table.html.erb
<% longest_duration = metrics.first.try(:duration) -%>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <% if columns.include?(:name) %><th>Name</th><% end %>
      <% if columns.include?(:identifier) %><th>Identifier</th><% end %>
      <% if columns.include?(:action) %><th>Action</th><% end %>
      <% if columns.include?(:when) %><th>When</th><% end %>
      <% if columns.include?(:duration) %><th>Duration (ms)</th><% end %>
    </tr>
  </thead>
  <tbody>
    <% for metric in metrics -%>
      <%= render :partial => 'metric_row', :locals => {
        :indent => 0,
        :columns => columns,
        :metric => metric,
        :longest_duration => longest_duration,
        :include_children => include_children
      } %>
    <% end -%>
  </tbody>
</table>

app/views/system_metrics/metrics/_portlet.html.erb
<div class="portlet">
  <h2><%= category.titleize %></h2>
  <table>
    <thead>
      <tr><th>ID</th><th>Action</th><th>Identifier</th><th>Duration</th></tr>
    </thead>
    <tbody>
      <% for metric in metrics -%>
        <tr>
          <td><%= link_to metric.id, metric_path(metric) %></td>
          <td><%= metric.action %></td>
          <td><%= identifier(metric) %></td>
          <td><%= metric.duration %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</div>

app/views/system_metrics/metrics/_title_bar.html.erb
<div id="title-bar" class="span-24 last">
  <h2 id="page-title"><%= page_title %></h2>

  <% if @from_date.present? && @to_date.present? -%>
  <h4>Viewing <%= distance_of_time_in_words @from_date, @to_date %> 
    of metrics from <%= @from_date.strftime('%b %e, %Y at %H:%M %Z') %></h4>
  <% end -%>

  <% if @metric.present? -%>
    <h4>
      <% for parent in @metric.ancestors.reverse -%>
        <%= link_to parent.name, metric_path(parent) %> &gt;
      <% end -%>
      <%= @metric.name %>
    </h4>
  <% end -%>
</div>

app/views/system_metrics/metrics/admin.html.erb
<% set_title "System Metrics Administration" -%>
<% set_page_title "Administration" -%>
<% if @categories.all.size > 0 -%>
  <div id="menu-bar">
    <%= form_tag "#{metrics_path}/all", :method => :delete do -%>
      <%= submit_tag 'Delete All' %>
    <% end -%>
    <h2>Metrics</h2>
  </div>

  <table>
    <thead>
      <tr><th>Category</th><th>Count</th><th>Action</th></tr>
    <thead>
    <tbody>
    <% for category in @categories -%>
      <tr>
        <td><%= category.category.titleize %></td>
        <td><%= category.count %></td>
        <td>
        <%= form_tag metric_path(category.category), :method => :delete do %>
          <%= submit_tag 'Delete Category' %>
        <% end -%>
        </td>
      </tr>
    <% end -%>
    </tbody>
  </table>
<% else -%>
  <p>No metrics found</p>
<% end -%>

app/views/system_metrics/metrics/category.html.erb
<% set_title "#{params[:category].titleize} Category System Metrics" -%>
<% set_page_title params[:category].titleize -%>
<%= render :partial => "metric_table", 
  :locals => { :metrics => @metrics, :include_children => false, :columns => [:identifier, :action, :when, :duration] } %>

app/views/system_metrics/metrics/index.html.erb
<% set_title 'System Metrics Dashboard' -%>
<% set_page_title 'Dashboard' -%>
<% @category_metrics.each do |category, metrics| -%>
  <%= render :partial => "portlet", :locals => {:category => category, :metrics => metrics} %>
<% end -%>
<% if @category_metrics.empty? -%>
  <p>No metrics found</p>
<% end -%>
<div class="clear"></div>

app/views/system_metrics/metrics/show.html.erb
<% set_title "System Metric details for #{@metric.name}:#{@metric.id}" -%>
<% set_page_title "#{@metric.name}:#{@metric.id}" -%>

<div id="metric-details">
  <h2><%= @metric.duration %> ms</h2>
  <dl>
    <dt>When</dt>
    <dd><%= distance_of_time_in_words_to_now @metric.started_at, true %> ago</dd>
  <% @metric.payload.each do |key, value| -%>
    <dt><%= key.to_s.titleize %></dt>
    <dd><%= value.kind_of?(String) ? value : value.inspect %></dd>
  <% end -%>
  </dl>
</div>

<div id="metric-children">
  <h2>Child Metrics</h2>
  <%= render :partial => "metric_table",
    :locals => {
      :metrics => @metric.children.order('duration DESC'),
      :include_children => true, 
      :columns => [:name, :identifier, :duration]
    } %>
</div>

<div class="clear"></div>